# Generated by Django 3.1.5 on 2021-01-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210128_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
