# Generated by Django 3.1.5 on 2021-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iduser',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
