# Generated by Django 3.1.5 on 2021-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210130_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iduser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
