# Generated by Django 3.1.6 on 2021-02-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210208_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iduser',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
