# Generated by Django 3.1.6 on 2021-02-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210217_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='iduser',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
