# Generated by Django 3.1.6 on 2021-02-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210217_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iduser',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
