# Generated by Django 3.1.5 on 2021-01-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user'),
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='request_from',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='request_to',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='request_from_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendlist',
            name='request_to_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user'),
            preserve_default=False,
        ),
    ]
