# Generated by Django 3.1.5 on 2021-01-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20210129_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='request_from_id',
            new_name='request_from',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='request_to_id',
            new_name='request_to',
        ),
    ]
