# Generated by Django 3.1.5 on 2021-01-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_user'),
        ('messanger', '0004_delete_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
            ],
        ),
    ]
