# Generated by Django 3.1.5 on 2021-01-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user'),
        ('messanger', '0005_friendlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='RequestsToFriendList',
        ),
    ]
