# Generated by Django 3.1.5 on 2021-01-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0007_auto_20210130_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststofriendlist',
            old_name='idrequeststofriendlist',
            new_name='idrequeststofriendlis',
        ),
    ]
