# Generated by Django 3.1.5 on 2021-01-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0009_auto_20210130_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestsToFriendList',
        ),
    ]
