# Generated by Django 3.1.5 on 2021-01-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0013_requeststofriendlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestsToFriendList',
        ),
    ]
