# Generated by Django 3.1.5 on 2021-01-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0016_auto_20210130_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
