# Generated by Django 3.1.5 on 2021-01-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210130_2054'),
        ('messanger', '0019_auto_20210130_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friend2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='idfriends',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
