# Generated by Django 3.1.5 on 2021-01-31 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210130_2054'),
        ('messanger', '0020_auto_20210130_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idchat', models.AutoField(primary_key=True, serialize=False)),
                ('friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
                ('friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idmessage', models.AutoField(primary_key=True, serialize=False)),
                ('date_message', models.DateField()),
                ('from_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
                ('idchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messanger.chat')),
                ('to_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('idtext', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('idmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='messanger.message')),
            ],
        ),
    ]
