# Generated by Django 3.1.5 on 2021-01-31 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0021_chat_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
